name: OneTimeFortune
version: 1.1
description: Makes the fortune enchantment disappear after a use.
author: Final Child
website: http:/play-minecraft.co.kr/
main: io.github.fcreloaded.onetimefortune.OneTimeFortune
permissions:
  onetimefortune.keep:
    description: Allows you to keep your fortune enchantments.
    default: op